### ISSUE TITLE
convert site to blogdown, hugodown, or ?

### ISSUE THREAD

**Issue by kriemo** [rnabioco/cellar#24]
The current rmarkdown based website isn't ideal as we have to rerender all of the .Rmds each time new content is added. This becomes tedious to maintain due to the large # of packages and datasets used for each lecture, in addition to the long build time. Let's consider moving to another platform that will allow new content to be added without requiring reknitting of all of the content.

**Comment by jayhesselberth** [comment]
I'd use hugodown, it's the lightest weight of the two.

Alternatively you could convert to a package framework and use pkgdown to render the vignettes.

**Comment by kriemo** [comment]
great, thanks, i'll try out converting to hugodown on a separate branch.
